// @ts-check

// The "룩 만들기" and "항목 레퍼런스" groups mirror the inspector's own workflow
// grouping, so a control found on screen maps to one page here.
//
// Category labels are translated in
// i18n/<locale>/docusaurus-plugin-content-docs/current.json.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '시작하기',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/first-material'],
    },
    {
      type: 'category',
      label: '룩 만들기',
      collapsed: false,
      items: [
        'guides/inspector',
        'guides/basics',
        'guides/light-and-shadow',
        'guides/shadow-pattern',
        'guides/rim',
        'guides/depth-effects',
        'guides/detail-maps',
        'guides/character',
        'guides/outline',
        'guides/mesh-bakes',
        'guides/texture-modules',
        'guides/bulk-editing',
        'guides/face-sdf',
        'guides/mask-maker',
        'guides/ming-light-controller',
        'guides/tiled-materials',
      ],
    },
    {
      type: 'category',
      label: '내보내기',
      collapsed: false,
      items: [
        'workflow/character-manager',
        'workflow/liltoon-conversion',
        'workflow/build-optimization',
        'workflow/bake-and-restore',
      ],
    },
    {
      type: 'category',
      label: '플랫폼',
      collapsed: false,
      items: [
        'platforms/vrchat',
        'platforms/compatibility',
        'platforms/warudo',
      ],
    },
    {
      type: 'category',
      label: '항목 레퍼런스',
      items: [
        'reference/basics',
        'reference/light-and-shadow',
        'reference/rim',
        'reference/depth-effects',
        'reference/detail-maps',
        'reference/character',
        'reference/outline',
        'reference/validator',
      ],
    },
    {
      type: 'category',
      label: '내부 동작',
      items: [
        'internals/shader-structure',
        'internals/module-cost',
        'internals/bake-internals',
        'internals/conversion-internals',
        'internals/vrc-rules',
      ],
    },
    {
      type: 'category',
      label: '패치노트',
      // A generated index gives the navbar a link that never moves, however many
      // versions pile up. Version pages sort by a negative version code, so the
      // newest is first. Add one with: node scripts/new-patch-note.mjs <version>
      link: {
        type: 'generated-index',
        slug: '/changelog',
        title: '패치노트',
        description: '버전별 변경 사항입니다. 최신 버전이 위에 있습니다.',
      },
      items: [{type: 'autogenerated', dirName: 'changelog'}],
    },
    'troubleshooting',
    'limitations',
  ],
};

export default sidebars;
